name: SF Media
favicon: null
layout_spectrum: 0.07074743369594216
typography_spectrum: 0.10294702928513288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6866053447593004
  lightness: 0.7655922661069781
  saturation: 0.8706400899682194
  rhythmicContrast: 0.6189613481983542
purpose: []
