name: SF Media
favicon: null
layout_spectrum: 0.37896
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#282828'
    - '#ffffff'
    - '#505050'
    - '#cecece'
    - '#7e7e7e'
  brandStrength: 0.1875
  lightness: 0.7655922661069781
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
